const state={universities:[{name:'University of Akron',country:'United States',region:'North America',category:'Public',reference:'NAFSA',stage:'Discovery',last:'18 Jul 2026',next:'25 Jul 2026'},{name:'University of Leeds',country:'United Kingdom',region:'Europe',category:'Public',reference:'EAIE',stage:'Introduction',last:'12 Jul 2026',next:'22 Jul 2026'},{name:'Arizona State University',country:'United States',region:'North America',category:'Public',reference:'AIRC',stage:'Not Contacted',last:'—',next:'—'},{name:'GISMA University of Applied Sciences',country:'Germany',region:'Europe',category:'Private',reference:'Normal',stage:'Partnership',last:'15 Jul 2026',next:'—'}]};
const container=document.getElementById('viewContainer');
const nav=[...document.querySelectorAll('nav button[data-view]')];
function layout(title,subtitle,body){container.innerHTML=`<div class="view"><div class="title-row"><div><h1>${title}</h1><p>${subtitle}</p></div></div>${body}</div>`}
function dashboard(){layout('Good afternoon, Omkar','Here’s what is happening across university outreach today.',`<div class="cards"><div class="card"><span class="label">TOTAL UNIVERSITIES</span><strong>4,286</strong><small>+48 this month</small></div><div class="card"><span class="label">ACTIVE CONTACTS</span><strong>7,943</strong><small>1.9 per university</small></div><div class="card"><span class="label">FOLLOW-UPS DUE</span><strong>126</strong><small>18 due today</small></div><div class="card"><span class="label">NOT CONTACTED</span><strong>2,104</strong><small>49% of database</small></div></div><div class="grid2"><div class="panel"><h3>Outreach pipeline</h3>${[['Not Contacted',2104,100],['Introduction',842,40],['Discovery',216,16],['Partnership',74,7]].map(x=>`<div class="pipeline-row"><span>${x[0]}</span><div class="bar"><i style="width:${x[2]}%"></i></div><strong>${x[1]}</strong></div>`).join('')}</div><div class="panel"><h3>Recent activity</h3><div class="activity-item"><strong>University of Akron</strong><span>Follow-up logged · Today</span></div><div class="activity-item"><strong>University of Leeds</strong><span>Stage changed to Introduction · Yesterday</span></div><div class="activity-item"><strong>Arizona State University</strong><span>New university added · Yesterday</span></div></div></div>`)}
function universities(){layout('Universities','Search, filter and manage the central university database.',`<div class="toolbar"><input id="uniSearch" placeholder="Search universities..."><select><option>All countries</option><option>United States</option><option>United Kingdom</option><option>Germany</option></select><select><option>All stages</option><option>Not Contacted</option><option>Introduction</option><option>Discovery</option><option>Partnership</option></select></div><div class="table-wrap"><table><thead><tr><th>University</th><th>Country</th><th>Region</th><th>Category</th><th>Reference</th><th>Stage</th><th>Last contact</th><th>Next follow-up</th></tr></thead><tbody id="uniRows">${rows(state.universities)}</tbody></table></div>`);document.getElementById('uniSearch').addEventListener('input',e=>{document.getElementById('uniRows').innerHTML=rows(state.universities.filter(x=>x.name.toLowerCase().includes(e.target.value.toLowerCase())))})}
function rows(items){return items.map(x=>`<tr><td><strong>${x.name}</strong></td><td>${x.country}</td><td>${x.region}</td><td>${x.category}</td><td>${x.reference}</td><td><span class="pill">${x.stage}</span></td><td>${x.last}</td><td>${x.next}</td></tr>`).join('')}
function simple(title,subtitle,message){layout(title,subtitle,`<div class="panel empty"><h3>${message}</h3><p>This Version 1 screen is scaffolded and ready to connect to the Google Sheets backend.</p></div>`)}
const views={dashboard,universities,contacts:()=>simple('Contacts','Manage multiple contacts under each university.','Contact directory'),followups:()=>simple('Follow-ups','See due, overdue and upcoming outreach actions.','Follow-up queue'),activity:()=>simple('Activity','A chronological record of all outreach interactions.','Activity timeline'),import:()=>simple('Import','Upload Excel or CSV and review duplicates before import.','Import centre'),analytics:()=>simple('Analytics','Track pipeline progress and outreach coverage.','Outreach analytics'),settings:()=>simple('Settings','Manage users, lookup values and application settings.','System settings')};
function show(view){nav.forEach(b=>b.classList.toggle('active',b.dataset.view===view));(views[view]||dashboard)()}
nav.forEach(b=>b.addEventListener('click',()=>show(b.dataset.view)));
const modal=document.getElementById('modalBackdrop');document.getElementById('addUniversityBtn').onclick=()=>modal.classList.remove('hidden');document.getElementById('cancelModal').onclick=()=>modal.classList.add('hidden');
document.getElementById('universityForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);state.universities.unshift({name:f.get('universityName'),country:f.get('country'),region:'—',category:'—',reference:'Normal',stage:f.get('stage'),last:'—',next:'—'});modal.classList.add('hidden');e.target.reset();show('universities')});
document.getElementById('globalSearch').addEventListener('keydown',e=>{if(e.key==='Enter'){show('universities');setTimeout(()=>{const s=document.getElementById('uniSearch');if(s){s.value=e.target.value;s.dispatchEvent(new Event('input'))}},0)}});show('dashboard');